### ISSUE TITLE
[Documentation] Mettre à jour la documentation pour `k8s-deactivate`

### ISSUE THREAD

**Issue by maxgfr** [SocialGouv/actions#50]
Les inputs nécessaires à l'action sont : 

```
 kube-config:
    description: "The base64 of the kubeconfig"
  github-token:
    description: "GitHub Token as provided by secrets"
    default: ${{ github.token }}
    required: true
  rancherId:
    description: "The Rancher project ID, usually secrets.RANCHER_PROJECT_ID"
  socialgouvBaseDomain:
    description: "The base domain name, usually secrets.SOCIALGOUV_BASE_DOMAIN"
```

Or sur la documentation il n'est pas indiqué tout ces éléments
